### ISSUE TITLE
Parsing error when role end date set

### ISSUE THREAD

**Issue by rglss** [the-scouts/compass-interface-core#52]
When a role is full, but has an end date defined (i.e. CC) this throws a parsing error:

`unexpected value; permitted: 'Cancelled', 'Closed', 'Full', 'Pre provisional', 'Provisional' (type=value_error.const; given=Full Ending DD MMM YYYY; permitted=('Cancelled', 'Closed', 'Full', 'Pre provisional', 'Provisional'))`

**Comment by AA-Turner** [comment]
Version? Should have been fixed in 0.9.5

**Comment by AA-Turner** [comment]
Here: a02dff7

**Comment by rglss** [comment]
0.9.6 - Something's been lost somewhere it seems...

**Comment by AA-Turner** [comment]
Is the text exactly `Full Ending` with no left paren? If so it won't match. But that is odd, as you'd Compass would be able to serialise ending dates consistently...

**Comment by rglss** [comment]
Ahh found it - this error is being thrown on get_roles_tab rather than get_training_tab where the above patch is applied.

https://github.com/the-scouts/compass-interface-core/blob/098beca7a745ff6e09506e8cd1335a20f8e76cb1/compass/core/_scrapers/member.py#L289

**Comment by rglss** [comment]
Quick hack that works:
`status_with_details = cells[5].text_content().strip()
            if status_with_details.startswith("Full Review Due "):
                role_status = "Full"
                review_date = parse(status_with_details.removeprefix("Full Review Due "))
            elif status_with_details.startswith("Full Ending "):
                role_status = "Full"
                review_date = None
            else:
                role_status = status_with_details
                review_date = None`

**Comment by AA-Turner** [comment]
PR to fix - although bit unusual to have an end date in 2024 - most I see are for less than a year!

**Comment by AA-Turner** [comment]
Released `v0.9.7` to fix.

**Comment by rglss** [comment]
See PR comment - I don't think this patch will resolve the issue

**Comment by AA-Turner** [comment]
Released `v0.9.8` to fix the fix that didn't fix things.

**Comment by rglss** [comment]
Soz - I had a PR ready to roll but your first try beat me to it. Just too damn efficient Adam 😆

**Comment by AA-Turner** [comment]
Should have said - I'd've held off! 

Sorry for the ineptitude - but an interesting design decision to use parens in one place (training tab) and not in another (roles). I hope that the same data backs both, otherwise we may find some interesting data-sync bugs!

**Comment by rglss** [comment]
Yer, it really is. The good news is out of the whole county thats the only issue i've encountered!
