### ISSUE TITLE
Hierarchy bootstrap problem

### ISSUE THREAD

**Issue by AA-Turner** [the-scouts/compass-interface-core#7]
In order to use any hierarchy.Hierarchy methods, the user must know the compass ID and level (County, District etc) of the unit they are interested in investigating.

This is a user experience issue, as the library currently offers no way to find these out before using them -- even though we do get this information during the login process.

I suggest we save the currently authenticated user's top-level hierarchy ID and level. Do we then use these as defaults for hierarchy.Hierarchy methods silently, or should we make the user explicitly use e.g. Login.hierarchy_id and Login.hierarchy_level properties?

I want to maintain flexibility in the methods but if most uses will simply be getting the hierarchy of the current user then adding opinionated defaults seems reasonable.

cc: @rglss

**Comment by rglss** [comment]
Agreed - take the user top level hierarchy as default, unless explicitly provided as part of a call. 

Probably worth logging these at DEBUG level to make it clear whats going on as well.
