### ISSUE TITLE
0.11.0 missing form pypi repo

### ISSUE THREAD

**Issue by arbitrarypunter** [the-scouts/compass-interface-core#75]
Adam
Seems something has went wrong with the last release. Latest version available should be 0.11.0 but in pypi it is 0.10.4

Thanks

**Comment by AA-Turner** [comment]
Seems I merged the commits in the wrong order, so when I tagged v0.11.0, the version number hadn't been updated. 

Will release a new version with the latest changes shortly, thanks for pointing out!

**Comment by AA-Turner** [comment]
@arbitrarypunter Released v0.12
